
GET http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzEyNTc5OCwiZXhwIjoxNjk3MTQ3Mzk4fQ.TmnuN7Onkz2Eg_irlrB1mL1NglA3wIs-ZzJw-kB0sYo


###
DELETE http://localhost:5000/deleteUser/41
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzA3OTE1NywiZXhwIjoxNjk3MTAwNzU3fQ.2a_jK1ybkdX8mpwkLC6-U7eeMZrHY8BkNlhmMhPuk70 


###
PUT http://localhost:5000/updateUser/39
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzA3OTE1NywiZXhwIjoxNjk3MTAwNzU3fQ.2a_jK1ybkdX8mpwkLC6-U7eeMZrHY8BkNlhmMhPuk70
Content-Type: application/json

{
    "nombre": "Gustavo",
    "username":"GTV_129",
    "email": "gustavo@gmail.com"
}


###
PUT  http://localhost:5000/updatePassword/43
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzEyNTc5OCwiZXhwIjoxNjk3MTQ3Mzk4fQ.TmnuN7Onkz2Eg_irlrB1mL1NglA3wIs-ZzJw-kB0sYo

Content-Type: application/json

{
    "password_antiguio": "Ilovereggae.17",
    "password_nuevo": "User.1234"
}
###
PUT  http://localhost:5000/uploadImage/37

Content-Type: application/json

{
    "name_img": "GTV_129"
}

