
GET http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzIzMDQyNCwiZXhwIjoxNjk3MjUyMDI0fQ.bPmkRsJkdsvlB65LJQQmSfdAF68jUal80UhaauClxtM


###
DELETE http://localhost:5000/deleteUser/43
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIuMTIzIiwidXNlcl9pZCI6NDMsImVtYWlsIjoidXNlcm5ldzEyM0BhbGdvLmNvbSIsIm5vbWJyZSI6IlVzdWFyaW8gUHJ1ZWJhIiwiaWF0IjoxNjk3MjA2ODUzLCJleHAiOjE2OTcyMjg0NTN9.zIH_aq5n8BdKfejmvPwGzwbCJ7QzIjEC_O58chuOtS4 

###
PUT http://localhost:5000/updateUser/45
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzIzMDQyNCwiZXhwIjoxNjk3MjUyMDI0fQ.bPmkRsJkdsvlB65LJQQmSfdAF68jUal80UhaauClxtM
Content-Type: application/json

{
    "nombre": "Prueba",
    "username": "Usuario123"
}


###
PUT  http://localhost:5000/updatePassword/45
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c3Rhdm8xMjMiLCJ1c2VyX2lkIjozNiwiZW1haWwiOiJndXN0YXZvYmVyOThAZ21haWwuY29tIiwibm9tYnJlIjoiR3VzdGF2byIsImlhdCI6MTY5NzIzMDQyNCwiZXhwIjoxNjk3MjUyMDI0fQ.bPmkRsJkdsvlB65LJQQmSfdAF68jUal80UhaauClxtM
Content-Type: application/json

{
    "passwordAntiguo":"Gustavo.123", 
    "passwordNuevo":"Prueba.123"
}
###
PUT  http://localhost:5000/uploadImage/37

Content-Type: application/json

{
    "name_img": "GTV_129"
}

